# Generated by Django 5.2.7 on 2025-10-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag_type', models.CharField(choices=[('meal_type', 'Meal Type'), ('time_of_day', 'Time of Day'), ('temperature', 'Temperature')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tag_type', 'name'],
                'unique_together': {('name', 'tag_type')},
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='core.tag'),
        ),
    ]
