# Generated by Django 5.2.7 on 2025-10-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tag_menuitem_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
    ]
